# Generated by Django 5.1.7 on 2025-03-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BOOKING', 'Booking Date'), ('PICKUP', 'Origin Pickup Date'), ('CARGO_RECEIVED', 'Cargo Received Date'), ('QC', 'QC Date'), ('EXPORT_CLEARANCE', 'Export Clearance Date'), ('LOADING', 'Loading Date'), ('ETD', 'ETD Date'), ('ETA', 'ETA Date'), ('CAN', 'CAN Date'), ('UNLOADING', 'Unloading Date'), ('IMPORT_CLEARANCE', 'Import Clearance Date'), ('CFS_ETA', 'CFS ETA'), ('DO', 'DO Date'), ('CARGO_PICKUP', 'Cargo Pickup Date')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20)),
                ('obl_number', models.CharField(max_length=50)),
                ('pol', models.CharField(max_length=100)),
                ('pod', models.CharField(max_length=100)),
                ('etd', models.DateField()),
                ('eta', models.DateField()),
                ('vessel', models.CharField(max_length=100)),
                ('voyage', models.CharField(max_length=50)),
                ('cfs', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.company')),
                ('milestones', models.ManyToManyField(blank=True, to='shipments.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='HBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbl_number', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('packages', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_order', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.company')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.container')),
                ('milestones', models.ManyToManyField(blank=True, to='shipments.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='HAWB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb_number', models.CharField(max_length=50)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('delivery_order', models.CharField(max_length=50)),
                ('shipping_bill', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.company')),
                ('milestones', models.ManyToManyField(blank=True, to='shipments.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50)),
                ('obl_mawb', models.CharField(max_length=50)),
                ('hbl_hawb', models.CharField(max_length=50)),
                ('freight', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.company')),
                ('milestones', models.ManyToManyField(blank=True, to='shipments.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_bill_number', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('packages', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.company')),
                ('milestones', models.ManyToManyField(blank=True, to='shipments.milestone')),
            ],
        ),
    ]
