# Generated by Django 4.2 on 2023-12-31 14:00
from django.db import migrations
from django.utils import timezone

def create_milestones(apps, schema_editor):
    Milestone = apps.get_model('shipments', 'Milestone')
    
    milestones = [
        {
            'code': 'BOOKING',
            'name': 'Booking Date',
            'description': 'When the customer books the shipment for transportation',
        },
        {
            'code': 'PICKUP', 
            'name': 'Origin Pickup Date',
            'description': 'When the shipment is picked up from shipper’s place (warehouse)',
        },
        {
            'code': 'CARGO_RECEIVED',
            'name': 'Cargo Received Date',
            'description': 'When the shipment is received at the CFS physically',
        },
        {
            'code': 'QC',
            'name': 'QC Date',
            'description': 'Date when Quality Control check is completed for the shipment',
        },
        {
            'code': 'EXPORT_CLEARANCE',
            'name': 'Export Clearance Date', 
            'description': 'When shipment is cleared by customs for export',
        },
        {
            'code': 'LOADING',
            'name': 'Loading Date',
            'description': 'When shipment is loaded into container after clearance',
        },
        {
            'code': 'ETD',
            'name': 'ETD Date',
            'description': 'Estimated Time of Departure of vessel from origin port',
        },
        {
            'code': 'ETA',
            'name': 'ETA Date',
            'description': 'Estimated Time of Arrival at destination port',
        },
        {
            'code': 'CAN',
            'name': 'CAN Date',
            'description': 'Date Cargo Arrival Notice is sent to consignee',
        },
        {
            'code': 'UNLOADING',
            'name': 'Unloading Date',
            'description': 'When shipment is unloaded from container at destination',
        },
        {
            'code': 'IMPORT_CLEARANCE',
            'name': 'Import Clearance Date',
            'description': 'When shipment clears customs at destination',
        },
        {
            'code': 'CFS_ETA',
            'name': 'CFS ETA',
            'description': 'Estimated arrival at Container Freight Station',
        },
        {
            'code': 'DO',
            'name': 'DO Date',
            'description': 'When Delivery Order is issued to consignee',
        },
        {
            'code': 'CARGO_PICKUP',
            'name': 'Cargo Pickup Date',
            'description': 'When consignee picks up shipment from CFS',
        }
    ]

    for data in milestones:
        Milestone.objects.update_or_create(
            code=data['code'],
            defaults={
                'name': data['name'],
                'description': data['description'],
                'date': None,  # Date can be added later
                'is_active': True
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),  # Replace with your last migration
    ]

    operations = [
        migrations.RunPython(create_milestones),
    ]