# Generated by Django 5.1.7 on 2025-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_create_milestones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hawb',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'HAWB', 'verbose_name_plural': 'HAWBs'},
        ),
        migrations.AlterModelOptions(
            name='hbl',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'House Bill of Lading', 'verbose_name_plural': 'House Bills of Lading'},
        ),
        migrations.AddField(
            model_name='hawb',
            name='airline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hawb',
            name='chargeable_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hawb',
            name='mawb_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hawb',
            name='packages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered')], default='BOOKED', max_length=20),
        ),
        migrations.AddField(
            model_name='hbl',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hbl',
            name='driver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hbl',
            name='obl_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hbl',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hbl',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hbl',
            name='shipping_bill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hbl',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered')], default='BOOKED', max_length=20),
        ),
        migrations.AddField(
            model_name='hbl',
            name='truck_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hawb',
            name='hawb_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hbl',
            name='hbl_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='hbl',
            index=models.Index(fields=['hbl_number'], name='shipments_h_hbl_num_1eb253_idx'),
        ),
        migrations.AddIndex(
            model_name='hbl',
            index=models.Index(fields=['origin', 'destination'], name='shipments_h_origin_109a3c_idx'),
        ),
    ]
