# Generated by Django 5.1.7 on 2025-03-31 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_hawb_options_alter_hbl_options_hawb_airline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb_or_hbl', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('packages', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='cargo_details',
            field=models.ManyToManyField(related_name='containers', to='shipments.cargodetail'),
        ),
    ]
